{% set version = load_setup_py_data().get('version') %}

package:
    name: rapids-pytest-benchmark
    version: {{ version }}

source:
    path: ..

build:
    script: {{ PYTHON }} -m pip install . --no-deps
    noarch: python

requirements:

    host:
        - python

    run:
        - python
        - pytest-benchmark=3.2.3
        - pynvml
        - asvdb>=0.3.0
        - pygal
        - psutil
        - rmm>=0.19.0

test:
    imports:
        - rapids_pytest_benchmark

about:
    home: https://github.com/rapidsai/benchmark
    license: Apache 2.0
