{% set version = load_setup_py_data(setup_file='rapids_pytest_benchmark/setup.py').get('version') %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}

package:
    name: rapids-pytest-benchmark
    version: {{ version }}

source:
    path: ../../

build:
    number: {{ git_revision_count }}
    script: {{ PYTHON }} -m pip install ./rapids_pytest_benchmark --no-deps
    noarch: python

requirements:

    host:
        - python

    run:
        - python
        - pytest-benchmark=3.2.3
        - pynvml
        - asvdb>=0.3.0
        - pygal

test:
    imports:
        - rapids_pytest_benchmark

about:
    home: https://github.com/rapidsai/benchmark
    license: Apache 2.0
